### ISSUE TITLE
Modify README.md for hactoberfest

### ISSUE THREAD

**Issue by ManishS6** [ManishS6/OS_Jcomponent#4]
Add instructions related to hacktoberfest in the readme.md.

**Comment by Harshit2k1** [comment]
Please assign this issue to me

**Comment by ManishS6** [comment]
@Hastech77 here you go. cheers

**Comment by ManishS6** [comment]
@Hastech77 Now you can proceed working on guidelines.

**Comment by ManishS6** [comment]
Also do add the logo there
